# Generated by Django 2.2.5 on 2020-09-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200912_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='instance_book',
            new_name='instant_book',
        ),
    ]
